export const FAILED_SIGN_IN = 'FAILED_SIGN_IN';
export const FAILED_SIGN_UP = 'FAILED_SIGN_UP';
export const FAILED_LOGOUT = 'FAILED_LOGOUT';
export const SUCCESSFUL_SIGN_IN = 'SUCCESSFUL_SIGN_IN';
export const SUCCESSFUL_SIGN_UP = 'SUCCESSFUL_SIGN_UP';
export const SUCCESSFUL_LOGOUT = 'SUCCESSFUL_LOGOUT';